sudo: false
language: node_js
node_js:
  - 6
  - 7
script: 
  - npm test
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS koa_sequelize_resource;'
  - mysql -u root -e "CREATE USER 'tester'@'localhost' IDENTIFIED BY 'tester';"
  - mysql -u root -e "GRANT ALL ON koa_sequelize_resource.* TO 'tester'@'localhost';"